// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC690kbSsFm98n0gmjEd-v4ge0_RIona60',
    appId: '1:68942608713:web:e51375706b6198c8d58298',
    messagingSenderId: '68942608713',
    projectId: 'tourist-11bae',
    authDomain: 'tourist-11bae.firebaseapp.com',
    storageBucket: 'tourist-11bae.firebasestorage.app',
    measurementId: 'G-Y6W9J9YKPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7z6hZ12J2dIAePdTa5GjktSejAIMwnw',
    appId: '1:68942608713:android:3d9d3f11e9c7ddd9d58298',
    messagingSenderId: '68942608713',
    projectId: 'tourist-11bae',
    storageBucket: 'tourist-11bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQDmsnzsBibeJpfl1UAsRQ7qfE35PIBgc',
    appId: '1:68942608713:ios:6ebbae6b73a0f031d58298',
    messagingSenderId: '68942608713',
    projectId: 'tourist-11bae',
    storageBucket: 'tourist-11bae.firebasestorage.app',
    iosBundleId: 'com.example.touristGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQDmsnzsBibeJpfl1UAsRQ7qfE35PIBgc',
    appId: '1:68942608713:ios:6ebbae6b73a0f031d58298',
    messagingSenderId: '68942608713',
    projectId: 'tourist-11bae',
    storageBucket: 'tourist-11bae.firebasestorage.app',
    iosBundleId: 'com.example.touristGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC690kbSsFm98n0gmjEd-v4ge0_RIona60',
    appId: '1:68942608713:web:78d35cc232c71ec3d58298',
    messagingSenderId: '68942608713',
    projectId: 'tourist-11bae',
    authDomain: 'tourist-11bae.firebaseapp.com',
    storageBucket: 'tourist-11bae.firebasestorage.app',
    measurementId: 'G-C2J555NCCZ',
  );
}
